#!/bin/sh

# github-get

set -eu

usage() {
    cat <<EOF
$(basename ${0}) GITHUB_URL [VERSION]

Download, unpack, and softlink a github project (latest release by default) in
the current working directory.

EOF
}

die() { { echo "ERROR: ${@}" ; usage ; } >&2 ; exit 1 ; }

version_latest() {
    (
        cd $(mktemp -d)
        curl -sL "${1}/releases" >releases
        grep -Eo '[^/]+\.tar\.gz' releases >tarballs
        sed 's/\.tar\.gz//' tarballs >versions
        sort -Vo versions versions
        tail -1 versions
    )
}

if [ 1 -eq ${#} ]; then
    github_url="${1}"
    version="$(version_latest ${github_url})"
elif [ 2 -eq ${#} ]; then
    github_url="${1}"
    version="${2}"
else
    die "bad args"
fi
cd $(mktemp -d)
project="$(basename ${github_url})"
curl -sLo ${project}_${version}.tar.gz ${github_url}/archive/${version}.tar.gz
tar -xf ${project}_${version}.tar.gz
untarred_dir=$(find ${PWD} -mindepth 1 -maxdepth 1 -type d)
cd -
mv -v ${untarred_dir} ${PWD}
ln -vs $(basename ${untarred_dir}) ${project}
